import {useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {doc,onSnapshot} from 'firebase/firestore';
import {db} from '../../services/firebase';
import {useAuth} from '../../context/AuthContext';
import {useOrder} from '../../hooks/useOrder';
import {rupiah} from '../../utils/format';
import SellerMini from '../../components/seller/SellerMini';
import Notice from '../../components/common/Notice';
export default function ProductDetail(){const {id}=useParams();
const [p,setP]=useState(null);
const [seller,setSeller]=useState(null);
const {user}=useAuth();
const {createOrder,busy}=useOrder();
const nav=useNavigate();
useEffect(()=>onSnapshot(doc(db,'products',id),s=>setP(s.exists()?{id:s.id,...s.data()}:null)),[id]);
useEffect(()=>{if(p?.sellerUid)return onSnapshot(doc(db,'sellers',p.sellerUid),s=>setSeller(s.exists()?{uid:s.id,...s.data()}:null))},[p?.sellerUid]);
if(!p)return <div className="state">Produk tidak ditemukan.</div>;
const buy=async()=>{if(!user)return nav('/login?next=/product/'+id);
if(p.status!=='available'||p.stock<1)return;
const r=await createOrder(id);
nav(`/chat/${r.roomId}`)};
return <article className="detail"><img src={p.imageUrl} alt={p.title}/><div><span className="muted">ID PRODUK: <b>{p.productId||p.id}</b></span><h1>{p.title}</h1><h2>{rupiah(p.price)}</h2><p>{p.description}</p><p>Stok: {p.stock}</p><SellerMini seller={seller}/>{p.status==='in_transaction'&&<Notice type="warning">Produk sedang dalam transaksi. Pilih produk lain.</Notice>}{p.status==='available'&&<button className="button primary" onClick={buy} disabled={busy||p.stock<1}>{busy?'Membuat room...':'Buy'}</button>}</div></article>}
